### ISSUE TITLE
mnUpdate can't access pg extension

### ISSUE THREAD

**Issue by dancernogorsky** [tjmoses/postgraphile-plugin-many-create-update-delete#10]
I have a table that has a column that's using the citext extension. 

I'm able to use mnCreate fine, but mnUpdate throws with the following error shown below.

I'm using another postgraphile upsert plugin that can perform updates fine on the same table.

I was going to fork your repo next and try and debug, but I wanted to check to see if it's something simple I am overlooking first?

```
// smart tag
"goe_public.asset_alarm_point_meta": {
        "tags": {
          "mncud": true
        }
  }

// error
{
  "errors": [
    {
      "message": "type \"goe_public.citext\" does not exist",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "mnUpdateAlarmMessage"
      ],
      "extensions": {
        "exception": {
          "code": "42704",
          "severity": "ERROR",
          "position": "397"
        }
      }
    }
  ],
  "data": {
    "mnUpdateAlarmMessage": null
  }
}`

**Comment by tjmoses** [comment]
Check if the citext extension is in the goe_public schema. I know you can install it in any schema (or have it tied to none) and change the search path to find it, *but the batch update plugin [stores column types](https://github.com/tjmoses/postgraphile-plugin-batch-create-update-delete/blob/e1bf103c20ddbcb046e5efeb738c9bbfcba1d184/src/PostGraphileManyUpdatePlugin.ts#L320) it needs according to the type and schema to perform the [bulk update](https://github.com/tjmoses/postgraphile-plugin-batch-create-update-delete/blob/e1bf103c20ddbcb046e5efeb738c9bbfcba1d184/src/PostGraphileManyUpdatePlugin.ts#L369).

**Comment by dancernogorsky** [comment]
Thank you!

Thank was it. I moved the extension for the time being.
