### ISSUE TITLE
Curious on implementation here

### ISSUE THREAD

**Issue by markhalonen** [tjmoses/postgraphile-plugin-many-create-update-delete#16]
Hey @tjmoses, was just looking through the code and the `CASE` statements in the `UPDATE` stuck out to me:

https://github.com/tjmoses/postgraphile-plugin-batch-create-update-delete/blob/433049b4d4741f7db4143e5a65759f8d91cec501/src/PostGraphileManyUpdatePlugin.ts#L370

Would it be possible to only include the used SQL columns in the UPDATE statement? could it be something like `UPDATE t1 SET {...usedSqlColumns}=t2.val` and avoid the `CASE` statement? We haven't noticed any issues in behavior, just curious if there was a reason for all columns to be involved in the SQL statement.

**Comment by tjmoses** [comment]
Go [here](https://stackoverflow.com/questions/63290696/update-multiple-rows-using-postgresql) for more info. It's mainly around if the values can be null, then it can skip them to perform the inline update using the temporary table.
