### ISSUE TITLE
Return values from a batch update - only getting 1 back

### ISSUE THREAD

**Issue by redaikidoka** [tjmoses/postgraphile-plugin-many-create-update-delete#18]
I'm doing a batch update to update several records: 
<img width="508" alt="image" src="https://github.com/tjmoses/postgraphile-plugin-batch-create-update-delete/assets/4842817/5ae2d211-8f11-4676-a00a-feffc9975d1a">

But in the response, I only get details back for 1 of them:
<img width="510" alt="image" src="https://github.com/tjmoses/postgraphile-plugin-batch-create-update-delete/assets/4842817/e253db28-078e-49b5-92d2-8e5bdc09409b">

This is the query:
```
mutation updateEntityAddressBatch($clientMutationId: String!, $mnPatch: [EntityAddressPatch!]) {
    mnUpdateEntityAddress(input: { mnPatch: $mnPatch, clientMutationId: $clientMutationId }) {
      entityAddress {
        defaultIssueBulkChecks
        defaultPayee
      }
      clientMutationId
    }
  }
```

am I doing something wrong?

**Comment by tjmoses** [comment]
Nope, this is a known bug. Batch Updates along with the creates also have this issue. There is a pull request to partially fix the updates, but it is not complete nor does it use typescript properly so I did not accept it.
Anyways, I am looking for contributors or funding/donations to work on these issues. Feel free to help in any way. Thanks for spending time to report this.

**Comment by redaikidoka** [comment]
oh! Gotcha. Well, we would like to use your plugin for realz yo. What would motivate you to return batch info? Happy to donate. You can message me @ pstafford@geminiduplication.com

**Comment by redaikidoka** [comment]
Seriously, we'd love to fund you to make this upgrade.
