### ISSUE TITLE
Doesn't show up

### ISSUE THREAD

**Issue by kfrp** [tjmoses/postgraphile-plugin-many-create-update-delete#9]
Not sure what I'm doing wrong, but I tested this plugin with postgraphile v4.11.0 as well as v4.12.0-alpha.0, with both CLI and library options, with other plugins as well as alone. But no changes show up in my explorer or schema. Any ideas?

**Comment by tjmoses** [comment]
Are you confident you added the smart comment properly? Provide the full table and comment DDL, and I can check what you have.

**Comment by kfrp** [comment]
Ah that was it. I knew it was something very silly. Thanks++
